# Bekerja dengan File

File TXT

In [2]:
filepath = '/content/'

In [34]:
filetxt ='cda_class_not_clean.txt'
with open(filepath+filetxt, 'r') as file:
  # print(file)
  for line in file:
    print(line)
  # print(file.read())

registration_id;name;email;phone;age;city;province;active;class;score

RK20202395;Arief;arief@hotmail.com;628618317;41;Madiun;Jawa Timur;1;5;60.0

RK20202355;Amalia;amalia@hotmail.com;628947349;56;Batam;Kepulauan Riau;1;6;63.0

RK20202352;Putu;putu@gmail.com;628601097;42;Malang;Jawa Timur;1;5;69.0

RK20202350;Citra;citra@hotmail.com;628965407;36;Surakarta;Jawa Tengah;1;4;69.0

RK20202371;Budi;budi@google.com;628613620;56;Batam;Kepulauan Riau;1;6;65.0

RK20202354;Fajar;fajar@gmail.com;628172162;34;Salatiga;Jawa Tengah;0;4;85.0

RK20202385;Indra;indra@gmail.com;628455732;33;Purwokerto;Jawa Tengah;1;4;60.0

RK20202387;Intan;intan@gmail.com;628476879;34;Salatiga;Jawa Tengah;0;4;98.0

RK20202406;Kusuma;kusuma@gmail.com;628012212;51;Palangkaraya;Kalimantan Tengah;1;6;

RK20202366;Deden;deden@google.com;628971836;20;Sungai Penuh;Jambi;1;2;91.0

RK20202433;Tuti;tuti@google.com;628263541;46;Surabaya;Jawa Timur;1;5;0.0

RK20202417;Anita;;628623943;50;Banjarmasin;Kalimantan Selatan;0;6;59.0

RK20202389;Ari;ari@gmail.com;628149660;42;Malang;Jawa Timur;1;5;0.0

RK20202363;Made;made@samsung.com;628844306;31;Magelang;Jawa Tengah;0;4;65.0

RK20202358;Puspita;puspita@google.com;628764029;57;Tanjungpinang;Kepulauan Riau;1;6;66.0

RK20202439;Abdul;abdul@gmail.com;628989064;54;Samarinda;Kalimantan Timur;0;6;59.0

RK20202409;Wulandari;wulandari@gmail.com;628833542;52;Balikpapan;Kalimantan Timur;1;6;0.0

RK20202404;Maria;maria@gmail.com;628668471;47;Pontianak;Kalimantan Barat;1;5;0.0

RK20202357;Amelia;amelia@ymail.com;628375103;59;Metro;Lampung;1;6;0.0

RK20202361;Rahmawati;rahmawati@gmail.com;628543079;35;Semarang;Jawa Tengah;1;4;100.0

RK20202375;Ratih;ratih@gmail.com;628336072;19;;Jakarta;0;1;81.0

RK20202435;Setiawan;setiawan@samsung.com;628969920;48;Singkawang;Kalimantan Barat;0;5;55.0

RK20202391;Budi;budi@gmail.com;628823013;57;Tanjungpinang;Kepulauan Riau;1;6;0.0

RK20202405;Rini;;628027521;46;Surabaya;Jawa Timur;0;5;72.0

RK20202435;Setiawan;setiawan@samsung.com;628969920;48;Singkawang;Kalimantan Barat;0;5;55.0

RK20202365;Puji;puji@samsung.com;628038302;27;Depok;Jawa Barat;1;2;75.0

RK20202420;Widya;widya@gmail.com;628953687;22;Bandung;Jawa Barat;1;2;66.0

RK20202415;Angga;angga@ymail.com;628637906;52;Balikpapan;Kalimantan Timur;1;6;0.0

RK20202421;Puji;puji@facebook.com;628402424;34;Salatiga;Jawa Tengah;1;4;64.0

RK20202425;Aulia;aulia@ymail.com;628547207;53;Bontang;Kalimantan Timur;1;6;50.0

RK20202348;Eva;eva@rakamin.com;628702735;42;Malang;Jawa Timur;0;5;0.0

RK20202353;Nurul;nurul@gmail.com;628687911;17;;Jakarta;0;1;79.0

RK20202388;Yunita;yunita@gmail.com;628913735;55;Tarakan;Kalimantan Utara;1;6;89.0

RK20202380;Gogon;gogon@google.com;628255878;27;Depok;Jawa Barat;1;2;76.0

RK20202348;Eva;eva@rakamin.com;628702735;42;Malang;Jawa Timur;0;5;80.0

RK20202414;Puput;puput@facebook.com;628891925;24;Bogor;Jawa Barat;1;2;67.0

RK20202363;Made;made@samsung.com;628844306;31;Magelang;Jawa Tengah;0;4;65.0

RK20202435;Setiawan;setiawan@samsung.com;628969920;48;Singkawang;Kalimantan Barat;0;5;0.0

RK20202358;Puspita;puspita@google.com;628764029;57;Tanjungpinang;Kepulauan Riau;1;6;0.0

RK20202371;Budi;budi@google.com;628613620;56;Batam;Kepulauan Riau;1;6;0.0

RK20202407;Wahyuni;wahyuni@samsung.com;628629014;46;Surabaya;Jawa Timur;1;5;0.0

RK20202407;Wahyuni;;628629014;46;Surabaya;Jawa Timur;1;5;63.0

RK20202377;Rizky;rizky@samsung.com;628392304;42;Malang;Jawa Timur;1;5;74.0

RK20202426;Een;een@facebook.com;628018377;15;Kota Administrasi Jakarta Barat;Jakarta;1;1;74.0

RK20202419;Achmad;achmad@ymail.com;628364382;44;Pasuruan;Jawa Timur;1;5;0.0

RK20202394;Sari;sari@google.com;628424396;26;Cirebon;Jawa Barat;0;2;86.0

RK20202409;Wulandari;wulandari@gmail.com;628833542;52;Balikpapan;Kalimantan Timur;1;6;83.0

RK20202347;Firman;firman@google.com;628638112;59;Metro;Lampung;1;6;0.0

RK20202390;Wulan;wulan@rocketmail.com;628361563;19;Kota Administrasi Jakarta Utara;Jakarta;1;1;73.0

RK20202398;Lukman;lukman@facebook.com;628294756;49;Banjarbaru;Kalimantan Selatan;0;5;95.0

RK20202436;Munaroh;munaroh@hotmail.com;628636716;15;;Jakarta;0;1;91.0

RK20202423;Ade;ade@gmail.com;628873409;51;Palangkaraya;Kalimantan Tengah;0;6;0.0

RK20202417;Anita;anita@gmail.com;628623943;50;Banjarmasin;Kalimantan Selatan;0;6;0.0

RK20202412;Kurnia;kurnia@gmail.com;628414294;39;Blitar;Jawa Timur;0;4;96.0

RK20202432;Astuti;astuti@ymail.com;628628806;52;Balikpapan;Kalimantan Timur;0;6;97.0

RK20202382;Kartika;kartika@gmail.com;628715317;27;Depok;Jawa Barat;0;2;59.0

RK20202359;Dadan;dadan@facebook.com;628952082;19;Kota Administrasi Jakarta Utara;Jakarta;1;1;63.0

RK20202376;Hafizh;hafizh@google.com;628535862;58;Bandar Lampung;Lampung;1;6;82.0

RK20202440;Ria;ria@gmail.com;628535849;56;Batam;Kepulauan Riau;0;6;58.0

RK20202441;Putra;putra@gmail.com;628205046;51;Palangkaraya;Kalimantan Tengah;1;6;

RK20202427;Rina;rina@gmail.com;628516075;54;Samarinda;Kalimantan Timur;1;6;0.0

RK20202406;Kusuma;kusuma@gmail.com;628012212;51;Palangkaraya;Kalimantan Tengah;1;6;0.0

RK20202349;Bagus;bagus@hotmail.com;628816223;16;Kota Administrasi Jakarta Pusat;Jakarta;1;1;84.0

RK20202393;Nugroho;nugroho@gmail.com;628430860;39;Blitar;Jawa Timur;0;4;68.0

RK20202386;Hendra;hendra@hotmail.com;628452630;58;Bandar Lampung;Lampung;1;6;75.0

RK20202349;Bagus;bagus@hotmail.com;628816223;16;Kota Administrasi Jakarta Pusat;Jakarta;1;1;84.0

RK20202416;Diah;diah@samsung.com;628007342;30;Banjar;Jawa Barat;1;4;85.0

RK20202430;Saputra;saputra@google.com;628420164;37;Tegal;Jawa Tengah;1;4;67.0

RK20202364;Komar;komar@google.com;628199543;49;Banjarbaru;Kalimantan Selatan;1;5;0.0

RK20202418;Lestari;lestari@gmail.com;628884683;30;Banjar;Jawa Barat;1;4;94.0

RK20202374;Eko;eko@gmail.com;628530222;28;Sukabumi;Jawa Barat;1;2;78.0

RK20202363;Made;made@samsung.com;628844306;31;Magelang;Jawa Tengah;0;4;65.0

RK20202389;Ari;ari@gmail.com;628149660;42;Malang;Jawa Timur;1;5;82.0

RK20202349;Bagus;bagus@hotmail.com;628816223;16;Kota Administrasi Jakarta Pusat;Jakarta;1;1;84.0

RK20202391;Budi;budi@gmail.com;628823013;57;Tanjungpinang;Kepulauan Riau;1;6;70.0

RK20202413;Aditya;aditya@gmail.com;628192927;49;Banjarbaru;Kalimantan Selatan;1;5;59.0

RK20202424;Saripah;saripah@google.com;628217629;38;Batu;Jawa Timur;1;4;76.0

RK20202397;Utami;utami@hotmail.com;628144623;40;Kediri;Jawa Timur;1;5;74.0

RK20202344;Nina;;628198157;57;Tanjungpinang;Kepulauan Riau;1;6;80.0

RK20202360;Diana;diana@ymail.com;628161800;18;;Jakarta;0;1;87.0

RK20202398;Lukman;lukman@facebook.com;628294756;49;Banjarbaru;Kalimantan Selatan;0;5;95.0

RK20202405;Rini;rini@samsung.com;628027521;46;Surabaya;Jawa Timur;0;5;0.0

RK20202346;Prima;prima@ymail.com;628755450;16;Kota Administrasi Jakarta Pusat;Jakarta;1;1;55.0

RK20202438;Arif;arif@gmail.com;628026203;56;Batam;Kepulauan Riau;0;6;0.0

RK20202403;Muhamad;muhamad@gmail.com;628246331;40;Kediri;Jawa Timur;0;5;100.0

RK20202443;Ilham;ilham@gmail.com;628680755;29;Tasikmalaya;Jawa Barat;1;2;52.0

RK20202437;Yunus;yunus@facebook.com;628561783;50;Banjarmasin;Kalimantan Selatan;0;6;66.0

RK20202379;Yulia;yulia@samsung.com;628291390;53;Bontang;Kalimantan Timur;1;6;68.0

RK20202408;Agustina;;628129314;26;Cirebon;Jawa Barat;1;2;59.0

RK20202428;Adi;adi@gmail.com;628238365;35;Semarang;Jawa Tengah;0;4;91.0

RK20202373;Devi;devi@hotmail.com;628048683;37;Tegal;Jawa Tengah;1;4;60.0

RK20202418;Lestari;lestari@gmail.com;628884683;30;Banjar;Jawa Barat;1;4;94.0

RK20202392;Dudung;dudung@facebook.com;628432009;39;Blitar;Jawa Timur;1;4;53.0

RK20202419;Achmad;achmad@ymail.com;628364382;44;Pasuruan;Jawa Timur;1;5;53.0

RK20202398;Lukman;lukman@facebook.com;628294756;49;Banjarbaru;Kalimantan Selatan;0;5;0.0

RK20202427;Rina;rina@gmail.com;628516075;54;Samarinda;Kalimantan Timur;1;6;84.0

RK20202434;Mamat;mamat@google.com;628875218;32;Pekalongan;Jawa Tengah;0;4;65.0

RK20202392;Dudung;dudung@facebook.com;628432009;39;Blitar;Jawa Timur;1;4;53.0

RK20202370;Fitria;fitria@gmail.com;628923593;47;Pontianak;Kalimantan Barat;1;5;89.0

RK20202431;Endang;endang@facebook.com;628038272;25;;Jawa Barat;0;2;65.0

RK20202411;Hidayat;hidayat@hotmail.com;628493696;17;;Jakarta;0;1;100.0

RK20202347;Firman;firman@google.com;628638112;59;Metro;Lampung;1;6;93.0

RK20202351;Yuni;yuni@google.com;628714465;16;;Jakarta;0;1;87.0

RK20202413;Aditya;aditya@gmail.com;628192927;49;Banjarbaru;Kalimantan Selatan;1;5;0.0

RK20202429;Anggraini;anggraini@rocketmail.com;628882355;43;Mojokerto;Jawa Timur;0;5;0.0

RK20202351;Yuni;yuni@google.com;628714465;16;;Jakarta;0;1;87.0

RK20202364;Komar;komar@google.com;628199543;49;Banjarbaru;Kalimantan Selatan;1;5;75.0

RK20202433;Tuti;tuti@google.com;628263541;46;Surabaya;Jawa Timur;1;5;51.0

RK20202425;Aulia;aulia@ymail.com;628547207;53;Bontang;Kalimantan Timur;1;6;50.0

RK20202352;Putu;putu@gmail.com;628601097;42;Malang;Jawa Timur;1;5;0.0

RK20202388;Yunita;yunita@gmail.com;628913735;55;Tarakan;Kalimantan Utara;1;6;0.0

RK20202441;Putra;putra@gmail.com;628205046;51;Palangkaraya;Kalimantan Tengah;1;6;0.0

RK20202377;Rizky;rizky@samsung.com;628392304;42;Malang;Jawa Timur;1;5;0.0

RK20202437;Yunus;yunus@facebook.com;628561783;50;Banjarmasin;Kalimantan Selatan;0;6;0.0

RK20202440;Ria;ria@gmail.com;628535849;56;Batam;Kepulauan Riau;0;6;0.0

RK20202410;Rizki;rizki@gmail.com;628372506;57;Tanjungpinang;Kepulauan Riau;0;6;0.0

RK20202369;Endah;endah@rakamin.com;628315789;53;Bontang;Kalimantan Timur;1;6;58.0

RK20202368;Handayani;handayani@gmail.com;628536204;20;;Jambi;0;2;95.0

RK20202415;Angga;angga@ymail.com;628637906;52;Balikpapan;Kalimantan Timur;1;6;71.0

RK20202381;Retno;retno@gmail.com;628543058;56;Batam;Kepulauan Riau;1;6;0.0

RK20202402;Hadi;hadi@ymail.com;628858507;29;Tasikmalaya;Jawa Barat;1;2;97.0

RK20202356;Didin;didin@facebook.com;628893056;49;Banjarbaru;Kalimantan Selatan;1;5;0.0

RK20202369;Endah;endah@rakamin.com;628315789;53;Bontang;Kalimantan Timur;1;6;0.0

RK20202381;Retno;retno@gmail.com;628543058;56;Batam;Kepulauan Riau;1;6;57.0

RK20202402;Hadi;hadi@ymail.com;628858507;29;Tasikmalaya;Jawa Barat;1;2;97.0

RK20202395;Arief;arief@hotmail.com;628618317;41;Madiun;Jawa Timur;1;5;0.0

RK20202369;Endah;endah@rakamin.com;628315789;53;Bontang;Kalimantan Timur;1;6;58.0

RK20202429;Anggraini;anggraini@rocketmail.com;628882355;43;Mojokerto;Jawa Timur;0;5;94.0

RK20202432;Astuti;astuti@ymail.com;628628806;52;Balikpapan;Kalimantan Timur;0;6;0.0

RK20202438;Arif;arif@gmail.com;628026203;56;Batam;Kepulauan Riau;0;6;95.0

RK20202362;Pratiwi;pratiwi@gmail.com;628341079;26;Cirebon;Jawa Barat;1;2;76.0

RK20202370;Fitria;fitria@gmail.com;628923593;47;Pontianak;Kalimantan Barat;1;5;0.0

RK20202384;Raden;raden@rakamin.com;628869259;17;Kota Administrasi Jakarta Selatan;Jakarta;1;1;87.0

RK20202426;Een;een@facebook.com;628018377;15;Kota Administrasi Jakarta Barat;Jakarta;1;1;74.0

RK20202399;Irma;irma@rakamin.com;628494954;34;Salatiga;Jawa Tengah;0;4;88.0

RK20202399;Irma;irma@rakamin.com;628494954;34;Salatiga;Jawa Tengah;0;4;88.0

RK20202396;Wisnu;wisnu@google.com;628890278;33;Purwokerto;Jawa Tengah;1;4;71.0

RK20202386;Hendra;hendra@hotmail.com;628452630;58;Bandar Lampung;Lampung;1;6;0.0

RK20202439;Abdul;abdul@gmail.com;628989064;54;Samarinda;Kalimantan Timur;0;6;59.0

RK20202397;Utami;utami@hotmail.com;628144623;40;Kediri;Jawa Timur;1;5;74.0

RK20202400;Dina;dina@hotmail.com;628474848;24;Bogor;Jawa Barat;1;2;99.0

RK20202419;Achmad;achmad@ymail.com;628364382;44;Pasuruan;Jawa Timur;1;5;53.0

RK20202401;Abdul;abdul@samsung.com;628480456;25;Cimahi;Jawa Barat;1;2;81.0

RK20202397;Utami;utami@hotmail.com;628144623;40;Kediri;Jawa Timur;1;5;74.0

RK20202367;Rahayu;rahayu@gmail.com;628558962;27;Depok;Jawa Barat;1;2;60.0

RK20202356;Didin;;628893056;49;Banjarbaru;Kalimantan Selatan;1;5;61.0

RK20202417;Anita;;628623943;50;Banjarmasin;Kalimantan Selatan;0;6;59.0

RK20202376;Hafizh;hafizh@google.com;628535862;58;Bandar Lampung;Lampung;1;6;0.0

RK20202344;Nina;nina@gmail.com;628198157;57;Tanjungpinang;Kepulauan Riau;1;6;0.0

RK20202377;Rizky;rizky@samsung.com;628392304;42;Malang;Jawa Timur;1;5;74.0

RK20202439;Abdul;abdul@gmail.com;628989064;54;Samarinda;Kalimantan Timur;0;6;0.0

RK20202372;Vicky;vicky@google.com;628298812;27;Depok;Jawa Barat;0;2;81.0

RK20202345;Dyah;dyah@gmail.com;628306496;24;;Jawa Barat;0;2;66.0

RK20202422;Bayu;bayu@gmail.com;628604813;39;Blitar;Jawa Timur;0;4;89.0

RK20202410;Rizki;rizki@gmail.com;628372506;57;Tanjungpinang;Kepulauan Riau;0;6;67.0

RK20202442;Kokom;kokom@facebook.com;628718477;23;;Jawa Barat;0;2;73.0

RK20202378;Kurniawan;kurniawan@gmail.com;628516417;22;Bandung;Jawa Barat;1;2;85.0

RK20202357;Amelia;amelia@ymail.com;628375103;59;Metro;Lampung;1;6;67.0

RK20202404;Maria;maria@gmail.com;628668471;47;Pontianak;Kalimantan Barat;1;5;71.0

RK20202379;Yulia;yulia@samsung.com;628291390;53;Bontang;Kalimantan Timur;1;6;0.0

RK20202425;Aulia;aulia@ymail.com;628547207;53;Bontang;Kalimantan Timur;1;6;0.0

RK20202398;Lukman;lukman@facebook.com;628294756;49;Banjarbaru;Kalimantan Selatan;0;5;95.0

RK20202392;Dudung;dudung@facebook.com;628432009;39;Blitar;Jawa Timur;1;4;53.0

RK20202410;Rizki;rizki@gmail.com;628372506;57;Tanjungpinang;Kepulauan Riau;0;6;67.0

RK20202355;Amalia;amalia@hotmail.com;628947349;56;Batam;Kepulauan Riau;1;6;0.0

RK20202406;Kusuma;kusuma@gmail.com;628012212;51;Palangkaraya;Kalimantan Tengah;1;6;

RK20202383;Novi;novi@rakamin.com;628889657;37;Tegal;Jawa Tengah;1;4;65.0

RK20202423;Ade;ade@gmail.com;628873409;51;Palangkaraya;Kalimantan Tengah;0;6;

RK20202360;Diana;diana@ymail.com;628161800;18;;Jakarta;0;1;87.0

In [11]:
with open(filepath+filetxt, 'r') as file:
  print(type(file))

<class '_io.TextIOWrapper'>

File CSV

In [ ]:
import csv

filecsv = 'cda_customer.csv'
with open(filepath+filecsv, mode='r') as file:
  # print(file)
  reader = csv.reader(file)
  # print(type(reader))
  # print(reader)
  for row in reader:
    print(row)

File JSON

In [38]:
import json

filejson = 'city-data.json'
with open(filepath+filejson, 'r') as file:

  read_json = json.load(file)
  data_properties = read_json['features'][1]['properties']
  # print(read_json)
  # print(read_json['features'][0])
  # print(type(read_json))
  # print(type(read_json['features'][0]))
  print(data_properties)

{'name': 'Tokyo', 'population': '13.35', 'country': 'Japan', 'coastal': 'true'}

# Struktur Data Pandas

Series

In [4]:
import pandas as pd

angka = [1,2,3,4.5,5]
identitas = {
    'Nama': 'Gamal',
    'Umur':29,
    'Alamat':'Jln. Tambak'
}

In [2]:
print(type(angka))
pd.Series(angka)

<class 'list'>

0    1.0
1    2.0
2    3.0
3    4.5
4    5.0
dtype: float64

In [3]:
print(type(identitas))
pd.Series(identitas)

<class 'dict'>

Nama            Gamal
Umur               29
Alamat    Jln. Tambak
dtype: object

In [37]:
nilai_pajak = [10,20,30]
label_pajak = ['PPh 21', 'PPN', 'PBB']

series_pajak = pd.Series(data=nilai_pajak, index=label_pajak)
series_pajak

PPh 21    10
PPN       20
PBB       30
dtype: int64

DataFrame

In [25]:
data_pengeluaran = {
    'Tanggal':['2025-05-01', '2025-05-01', '2025-05-02', '2025-05-02'],
    'Kategori':['Makanan', 'Transportasi', 'Makanan', 'Hiburan'],
    'Nominal (Rp)':[25000, 10000, 50000, 30000]
}

df_pengeluaran = pd.DataFrame(data_pengeluaran)
type(df_pengeluaran)

pandas.core.frame.DataFrame