# Bekerja dengan File

File TXT

In [ ]:
filepath = '/content/'

In [67]:
filetxt ='cda_class_not_clean.txt'
with open(filepath+filetxt, 'r') as file:
  # print(file)
  for line in file:
    print(line)
  # print(file.read())

registration_id;name;email;phone;age;city;province;active;class;score

RK20202395;Arief;arief@hotmail.com;628618317;41;Madiun;Jawa Timur;1;5;60.0

RK20202355;Amalia;amalia@hotmail.com;628947349;56;Batam;Kepulauan Riau;1;6;63.0

RK20202352;Putu;putu@gmail.com;628601097;42;Malang;Jawa Timur;1;5;69.0

RK20202350;Citra;citra@hotmail.com;628965407;36;Surakarta;Jawa Tengah;1;4;69.0

RK20202371;Budi;budi@google.com;628613620;56;Batam;Kepulauan Riau;1;6;65.0

RK20202354;Fajar;fajar@gmail.com;628172162;34;Salatiga;Jawa Tengah;0;4;85.0

RK20202385;Indra;indra@gmail.com;628455732;33;Purwokerto;Jawa Tengah;1;4;60.0

RK20202387;Intan;intan@gmail.com;628476879;34;Salatiga;Jawa Tengah;0;4;98.0

RK20202406;Kusuma;kusuma@gmail.com;628012212;51;Palangkaraya;Kalimantan Tengah;1;6;

RK20202366;Deden;deden@google.com;628971836;20;Sungai Penuh;Jambi;1;2;91.0

RK20202433;Tuti;tuti@google.com;628263541;46;Surabaya;Jawa Timur;1;5;0.0

RK20202417;Anita;;628623943;50;Banjarmasin;Kalimantan Selatan;0;6;59.0

RK20202389;Ari;ari@gmail.com;628149660;42;Malang;Jawa Timur;1;5;0.0

RK20202363;Made;made@samsung.com;628844306;31;Magelang;Jawa Tengah;0;4;65.0

RK20202358;Puspita;puspita@google.com;628764029;57;Tanjungpinang;Kepulauan Riau;1;6;66.0

RK20202439;Abdul;abdul@gmail.com;628989064;54;Samarinda;Kalimantan Timur;0;6;59.0

RK20202409;Wulandari;wulandari@gmail.com;628833542;52;Balikpapan;Kalimantan Timur;1;6;0.0

RK20202404;Maria;maria@gmail.com;628668471;47;Pontianak;Kalimantan Barat;1;5;0.0

RK20202357;Amelia;amelia@ymail.com;628375103;59;Metro;Lampung;1;6;0.0

RK20202361;Rahmawati;rahmawati@gmail.com;628543079;35;Semarang;Jawa Tengah;1;4;100.0

RK20202375;Ratih;ratih@gmail.com;628336072;19;;Jakarta;0;1;81.0

RK20202435;Setiawan;setiawan@samsung.com;628969920;48;Singkawang;Kalimantan Barat;0;5;55.0

RK20202391;Budi;budi@gmail.com;628823013;57;Tanjungpinang;Kepulauan Riau;1;6;0.0

RK20202405;Rini;;628027521;46;Surabaya;Jawa Timur;0;5;72.0

RK20202435;Setiawan;setiawan@samsung.com;628969920;48;Singkawang;Kalimantan Barat;0;5;55.0

RK20202365;Puji;puji@samsung.com;628038302;27;Depok;Jawa Barat;1;2;75.0

RK20202420;Widya;widya@gmail.com;628953687;22;Bandung;Jawa Barat;1;2;66.0

RK20202415;Angga;angga@ymail.com;628637906;52;Balikpapan;Kalimantan Timur;1;6;0.0

RK20202421;Puji;puji@facebook.com;628402424;34;Salatiga;Jawa Tengah;1;4;64.0

RK20202425;Aulia;aulia@ymail.com;628547207;53;Bontang;Kalimantan Timur;1;6;50.0

RK20202348;Eva;eva@rakamin.com;628702735;42;Malang;Jawa Timur;0;5;0.0

RK20202353;Nurul;nurul@gmail.com;628687911;17;;Jakarta;0;1;79.0

RK20202388;Yunita;yunita@gmail.com;628913735;55;Tarakan;Kalimantan Utara;1;6;89.0

RK20202380;Gogon;gogon@google.com;628255878;27;Depok;Jawa Barat;1;2;76.0

RK20202348;Eva;eva@rakamin.com;628702735;42;Malang;Jawa Timur;0;5;80.0

RK20202414;Puput;puput@facebook.com;628891925;24;Bogor;Jawa Barat;1;2;67.0

RK20202363;Made;made@samsung.com;628844306;31;Magelang;Jawa Tengah;0;4;65.0

RK20202435;Setiawan;setiawan@samsung.com;628969920;48;Singkawang;Kalimantan Barat;0;5;0.0

RK20202358;Puspita;puspita@google.com;628764029;57;Tanjungpinang;Kepulauan Riau;1;6;0.0

RK20202371;Budi;budi@google.com;628613620;56;Batam;Kepulauan Riau;1;6;0.0

RK20202407;Wahyuni;wahyuni@samsung.com;628629014;46;Surabaya;Jawa Timur;1;5;0.0

RK20202407;Wahyuni;;628629014;46;Surabaya;Jawa Timur;1;5;63.0

RK20202377;Rizky;rizky@samsung.com;628392304;42;Malang;Jawa Timur;1;5;74.0

RK20202426;Een;een@facebook.com;628018377;15;Kota Administrasi Jakarta Barat;Jakarta;1;1;74.0

RK20202419;Achmad;achmad@ymail.com;628364382;44;Pasuruan;Jawa Timur;1;5;0.0

RK20202394;Sari;sari@google.com;628424396;26;Cirebon;Jawa Barat;0;2;86.0

RK20202409;Wulandari;wulandari@gmail.com;628833542;52;Balikpapan;Kalimantan Timur;1;6;83.0

RK20202347;Firman;firman@google.com;628638112;59;Metro;Lampung;1;6;0.0

RK20202390;Wulan;wulan@rocketmail.com;628361563;19;Kota Administrasi Jakarta Utara;Jakarta;1;1;73.0

RK20202398;Lukman;lukman@facebook.com;628294756;49;Banjarbaru;Kalimantan Selatan;0;5;95.0

RK20202436;Munaroh;munaroh@hotmail.com;628636716;15;;Jakarta;0;1;91.0

RK20202423;Ade;ade@gmail.com;628873409;51;Palangkaraya;Kalimantan Tengah;0;6;0.0

RK20202417;Anita;anita@gmail.com;628623943;50;Banjarmasin;Kalimantan Selatan;0;6;0.0

RK20202412;Kurnia;kurnia@gmail.com;628414294;39;Blitar;Jawa Timur;0;4;96.0

RK20202432;Astuti;astuti@ymail.com;628628806;52;Balikpapan;Kalimantan Timur;0;6;97.0

RK20202382;Kartika;kartika@gmail.com;628715317;27;Depok;Jawa Barat;0;2;59.0

RK20202359;Dadan;dadan@facebook.com;628952082;19;Kota Administrasi Jakarta Utara;Jakarta;1;1;63.0

RK20202376;Hafizh;hafizh@google.com;628535862;58;Bandar Lampung;Lampung;1;6;82.0

RK20202440;Ria;ria@gmail.com;628535849;56;Batam;Kepulauan Riau;0;6;58.0

RK20202441;Putra;putra@gmail.com;628205046;51;Palangkaraya;Kalimantan Tengah;1;6;

RK20202427;Rina;rina@gmail.com;628516075;54;Samarinda;Kalimantan Timur;1;6;0.0

RK20202406;Kusuma;kusuma@gmail.com;628012212;51;Palangkaraya;Kalimantan Tengah;1;6;0.0

RK20202349;Bagus;bagus@hotmail.com;628816223;16;Kota Administrasi Jakarta Pusat;Jakarta;1;1;84.0

RK20202393;Nugroho;nugroho@gmail.com;628430860;39;Blitar;Jawa Timur;0;4;68.0

RK20202386;Hendra;hendra@hotmail.com;628452630;58;Bandar Lampung;Lampung;1;6;75.0

RK20202349;Bagus;bagus@hotmail.com;628816223;16;Kota Administrasi Jakarta Pusat;Jakarta;1;1;84.0

RK20202416;Diah;diah@samsung.com;628007342;30;Banjar;Jawa Barat;1;4;85.0

RK20202430;Saputra;saputra@google.com;628420164;37;Tegal;Jawa Tengah;1;4;67.0

RK20202364;Komar;komar@google.com;628199543;49;Banjarbaru;Kalimantan Selatan;1;5;0.0

RK20202418;Lestari;lestari@gmail.com;628884683;30;Banjar;Jawa Barat;1;4;94.0

RK20202374;Eko;eko@gmail.com;628530222;28;Sukabumi;Jawa Barat;1;2;78.0

RK20202363;Made;made@samsung.com;628844306;31;Magelang;Jawa Tengah;0;4;65.0

RK20202389;Ari;ari@gmail.com;628149660;42;Malang;Jawa Timur;1;5;82.0

RK20202349;Bagus;bagus@hotmail.com;628816223;16;Kota Administrasi Jakarta Pusat;Jakarta;1;1;84.0

RK20202391;Budi;budi@gmail.com;628823013;57;Tanjungpinang;Kepulauan Riau;1;6;70.0

RK20202413;Aditya;aditya@gmail.com;628192927;49;Banjarbaru;Kalimantan Selatan;1;5;59.0

RK20202424;Saripah;saripah@google.com;628217629;38;Batu;Jawa Timur;1;4;76.0

RK20202397;Utami;utami@hotmail.com;628144623;40;Kediri;Jawa Timur;1;5;74.0

RK20202344;Nina;;628198157;57;Tanjungpinang;Kepulauan Riau;1;6;80.0

RK20202360;Diana;diana@ymail.com;628161800;18;;Jakarta;0;1;87.0

RK20202398;Lukman;lukman@facebook.com;628294756;49;Banjarbaru;Kalimantan Selatan;0;5;95.0

RK20202405;Rini;rini@samsung.com;628027521;46;Surabaya;Jawa Timur;0;5;0.0

RK20202346;Prima;prima@ymail.com;628755450;16;Kota Administrasi Jakarta Pusat;Jakarta;1;1;55.0

RK20202438;Arif;arif@gmail.com;628026203;56;Batam;Kepulauan Riau;0;6;0.0

RK20202403;Muhamad;muhamad@gmail.com;628246331;40;Kediri;Jawa Timur;0;5;100.0

RK20202443;Ilham;ilham@gmail.com;628680755;29;Tasikmalaya;Jawa Barat;1;2;52.0

RK20202437;Yunus;yunus@facebook.com;628561783;50;Banjarmasin;Kalimantan Selatan;0;6;66.0

RK20202379;Yulia;yulia@samsung.com;628291390;53;Bontang;Kalimantan Timur;1;6;68.0

RK20202408;Agustina;;628129314;26;Cirebon;Jawa Barat;1;2;59.0

RK20202428;Adi;adi@gmail.com;628238365;35;Semarang;Jawa Tengah;0;4;91.0

RK20202373;Devi;devi@hotmail.com;628048683;37;Tegal;Jawa Tengah;1;4;60.0

RK20202418;Lestari;lestari@gmail.com;628884683;30;Banjar;Jawa Barat;1;4;94.0

RK20202392;Dudung;dudung@facebook.com;628432009;39;Blitar;Jawa Timur;1;4;53.0

RK20202419;Achmad;achmad@ymail.com;628364382;44;Pasuruan;Jawa Timur;1;5;53.0

RK20202398;Lukman;lukman@facebook.com;628294756;49;Banjarbaru;Kalimantan Selatan;0;5;0.0

RK20202427;Rina;rina@gmail.com;628516075;54;Samarinda;Kalimantan Timur;1;6;84.0

RK20202434;Mamat;mamat@google.com;628875218;32;Pekalongan;Jawa Tengah;0;4;65.0

RK20202392;Dudung;dudung@facebook.com;628432009;39;Blitar;Jawa Timur;1;4;53.0

RK20202370;Fitria;fitria@gmail.com;628923593;47;Pontianak;Kalimantan Barat;1;5;89.0

RK20202431;Endang;endang@facebook.com;628038272;25;;Jawa Barat;0;2;65.0

RK20202411;Hidayat;hidayat@hotmail.com;628493696;17;;Jakarta;0;1;100.0

RK20202347;Firman;firman@google.com;628638112;59;Metro;Lampung;1;6;93.0

RK20202351;Yuni;yuni@google.com;628714465;16;;Jakarta;0;1;87.0

RK20202413;Aditya;aditya@gmail.com;628192927;49;Banjarbaru;Kalimantan Selatan;1;5;0.0

RK20202429;Anggraini;anggraini@rocketmail.com;628882355;43;Mojokerto;Jawa Timur;0;5;0.0

RK20202351;Yuni;yuni@google.com;628714465;16;;Jakarta;0;1;87.0

RK20202364;Komar;komar@google.com;628199543;49;Banjarbaru;Kalimantan Selatan;1;5;75.0

RK20202433;Tuti;tuti@google.com;628263541;46;Surabaya;Jawa Timur;1;5;51.0

RK20202425;Aulia;aulia@ymail.com;628547207;53;Bontang;Kalimantan Timur;1;6;50.0

RK20202352;Putu;putu@gmail.com;628601097;42;Malang;Jawa Timur;1;5;0.0

RK20202388;Yunita;yunita@gmail.com;628913735;55;Tarakan;Kalimantan Utara;1;6;0.0

RK20202441;Putra;putra@gmail.com;628205046;51;Palangkaraya;Kalimantan Tengah;1;6;0.0

RK20202377;Rizky;rizky@samsung.com;628392304;42;Malang;Jawa Timur;1;5;0.0

RK20202437;Yunus;yunus@facebook.com;628561783;50;Banjarmasin;Kalimantan Selatan;0;6;0.0

RK20202440;Ria;ria@gmail.com;628535849;56;Batam;Kepulauan Riau;0;6;0.0

RK20202410;Rizki;rizki@gmail.com;628372506;57;Tanjungpinang;Kepulauan Riau;0;6;0.0

RK20202369;Endah;endah@rakamin.com;628315789;53;Bontang;Kalimantan Timur;1;6;58.0

RK20202368;Handayani;handayani@gmail.com;628536204;20;;Jambi;0;2;95.0

RK20202415;Angga;angga@ymail.com;628637906;52;Balikpapan;Kalimantan Timur;1;6;71.0

RK20202381;Retno;retno@gmail.com;628543058;56;Batam;Kepulauan Riau;1;6;0.0

RK20202402;Hadi;hadi@ymail.com;628858507;29;Tasikmalaya;Jawa Barat;1;2;97.0

RK20202356;Didin;didin@facebook.com;628893056;49;Banjarbaru;Kalimantan Selatan;1;5;0.0

RK20202369;Endah;endah@rakamin.com;628315789;53;Bontang;Kalimantan Timur;1;6;0.0

RK20202381;Retno;retno@gmail.com;628543058;56;Batam;Kepulauan Riau;1;6;57.0

RK20202402;Hadi;hadi@ymail.com;628858507;29;Tasikmalaya;Jawa Barat;1;2;97.0

RK20202395;Arief;arief@hotmail.com;628618317;41;Madiun;Jawa Timur;1;5;0.0

RK20202369;Endah;endah@rakamin.com;628315789;53;Bontang;Kalimantan Timur;1;6;58.0

RK20202429;Anggraini;anggraini@rocketmail.com;628882355;43;Mojokerto;Jawa Timur;0;5;94.0

RK20202432;Astuti;astuti@ymail.com;628628806;52;Balikpapan;Kalimantan Timur;0;6;0.0

RK20202438;Arif;arif@gmail.com;628026203;56;Batam;Kepulauan Riau;0;6;95.0

RK20202362;Pratiwi;pratiwi@gmail.com;628341079;26;Cirebon;Jawa Barat;1;2;76.0

RK20202370;Fitria;fitria@gmail.com;628923593;47;Pontianak;Kalimantan Barat;1;5;0.0

RK20202384;Raden;raden@rakamin.com;628869259;17;Kota Administrasi Jakarta Selatan;Jakarta;1;1;87.0

RK20202426;Een;een@facebook.com;628018377;15;Kota Administrasi Jakarta Barat;Jakarta;1;1;74.0

RK20202399;Irma;irma@rakamin.com;628494954;34;Salatiga;Jawa Tengah;0;4;88.0

RK20202399;Irma;irma@rakamin.com;628494954;34;Salatiga;Jawa Tengah;0;4;88.0

RK20202396;Wisnu;wisnu@google.com;628890278;33;Purwokerto;Jawa Tengah;1;4;71.0

RK20202386;Hendra;hendra@hotmail.com;628452630;58;Bandar Lampung;Lampung;1;6;0.0

RK20202439;Abdul;abdul@gmail.com;628989064;54;Samarinda;Kalimantan Timur;0;6;59.0

RK20202397;Utami;utami@hotmail.com;628144623;40;Kediri;Jawa Timur;1;5;74.0

RK20202400;Dina;dina@hotmail.com;628474848;24;Bogor;Jawa Barat;1;2;99.0

RK20202419;Achmad;achmad@ymail.com;628364382;44;Pasuruan;Jawa Timur;1;5;53.0

RK20202401;Abdul;abdul@samsung.com;628480456;25;Cimahi;Jawa Barat;1;2;81.0

RK20202397;Utami;utami@hotmail.com;628144623;40;Kediri;Jawa Timur;1;5;74.0

RK20202367;Rahayu;rahayu@gmail.com;628558962;27;Depok;Jawa Barat;1;2;60.0

RK20202356;Didin;;628893056;49;Banjarbaru;Kalimantan Selatan;1;5;61.0

RK20202417;Anita;;628623943;50;Banjarmasin;Kalimantan Selatan;0;6;59.0

RK20202376;Hafizh;hafizh@google.com;628535862;58;Bandar Lampung;Lampung;1;6;0.0

RK20202344;Nina;nina@gmail.com;628198157;57;Tanjungpinang;Kepulauan Riau;1;6;0.0

RK20202377;Rizky;rizky@samsung.com;628392304;42;Malang;Jawa Timur;1;5;74.0

RK20202439;Abdul;abdul@gmail.com;628989064;54;Samarinda;Kalimantan Timur;0;6;0.0

RK20202372;Vicky;vicky@google.com;628298812;27;Depok;Jawa Barat;0;2;81.0

RK20202345;Dyah;dyah@gmail.com;628306496;24;;Jawa Barat;0;2;66.0

RK20202422;Bayu;bayu@gmail.com;628604813;39;Blitar;Jawa Timur;0;4;89.0

RK20202410;Rizki;rizki@gmail.com;628372506;57;Tanjungpinang;Kepulauan Riau;0;6;67.0

RK20202442;Kokom;kokom@facebook.com;628718477;23;;Jawa Barat;0;2;73.0

RK20202378;Kurniawan;kurniawan@gmail.com;628516417;22;Bandung;Jawa Barat;1;2;85.0

RK20202357;Amelia;amelia@ymail.com;628375103;59;Metro;Lampung;1;6;67.0

RK20202404;Maria;maria@gmail.com;628668471;47;Pontianak;Kalimantan Barat;1;5;71.0

RK20202379;Yulia;yulia@samsung.com;628291390;53;Bontang;Kalimantan Timur;1;6;0.0

RK20202425;Aulia;aulia@ymail.com;628547207;53;Bontang;Kalimantan Timur;1;6;0.0

RK20202398;Lukman;lukman@facebook.com;628294756;49;Banjarbaru;Kalimantan Selatan;0;5;95.0

RK20202392;Dudung;dudung@facebook.com;628432009;39;Blitar;Jawa Timur;1;4;53.0

RK20202410;Rizki;rizki@gmail.com;628372506;57;Tanjungpinang;Kepulauan Riau;0;6;67.0

RK20202355;Amalia;amalia@hotmail.com;628947349;56;Batam;Kepulauan Riau;1;6;0.0

RK20202406;Kusuma;kusuma@gmail.com;628012212;51;Palangkaraya;Kalimantan Tengah;1;6;

RK20202383;Novi;novi@rakamin.com;628889657;37;Tegal;Jawa Tengah;1;4;65.0

RK20202423;Ade;ade@gmail.com;628873409;51;Palangkaraya;Kalimantan Tengah;0;6;

RK20202360;Diana;diana@ymail.com;628161800;18;;Jakarta;0;1;87.0

In [ ]:
with open(filepath+filetxt, 'r') as file:
  print(type(file))

<class '_io.TextIOWrapper'>

File CSV

In [ ]:
import csv

filecsv = 'cda_customer.csv'
with open(filepath+filecsv, mode='r') as file:
  # print(file)
  reader = csv.reader(file)
  # print(type(reader))
  # print(reader)
  for row in reader:
    print(row)

File JSON

In [74]:
import json

filejson = 'city-data.json'
with open(filepath+filejson, 'r') as file:

  read_json = json.load(file)
  data_properties = read_json['features'][1]['properties']
  # print(read_json)
  # print(read_json['features'][0])
  # print(type(read_json))
  # print(type(read_json['features'][0]))
  print(data_properties)

{'name': 'Tokyo', 'population': '13.35', 'country': 'Japan', 'coastal': 'true'}

# Struktur Data Pandas

Series

In [209]:
import pandas as pd

angka = [1,2,3,4.5,5]
identitas = {
    'Nama': 'Gamal',
    'Umur':29,
    'Alamat':'Jln. Tambak'
}

In [210]:
print(type(angka))
pd.Series(angka)

<class 'list'>

0    1.0
1    2.0
2    3.0
3    4.5
4    5.0
dtype: float64

In [211]:
print(type(identitas))
pd.Series(identitas)

<class 'dict'>

Nama            Gamal
Umur               29
Alamat    Jln. Tambak
dtype: object

In [212]:
nilai_pajak = [10,20,30]
label_pajak = ['PPh 21', 'PPN', 'PBB']

series_pajak = pd.Series(data=nilai_pajak, index=label_pajak)
series_pajak

PPh 21    10
PPN       20
PBB       30
dtype: int64

DataFrame

In [213]:
data_pengeluaran = {
    'Tanggal':['2025-05-01', '2025-05-01', '2025-05-02', '2025-05-02'],
    'Kategori':['Makanan', 'Transportasi', 'Makanan', 'Hiburan'],
    'Nominal (Rp)':[25000, 10000, 50000, 30000]
}

df_pengeluaran = pd.DataFrame(data_pengeluaran)

In [214]:
df_pengeluaran.head(2)

      Tanggal      Kategori  Nominal (Rp)
0  2025-05-01       Makanan         25000
1  2025-05-01  Transportasi         10000

In [215]:
df_pengeluaran.tail(2)

      Tanggal Kategori  Nominal (Rp)
2  2025-05-02  Makanan         50000
3  2025-05-02  Hiburan         30000

In [216]:
df_pengeluaran.dtypes

Tanggal         object
Kategori        object
Nominal (Rp)     int64
dtype: object

In [217]:
df_pengeluaran.shape

(4, 3)

In [218]:
df_pengeluaran

      Tanggal      Kategori  Nominal (Rp)
0  2025-05-01       Makanan         25000
1  2025-05-01  Transportasi         10000
2  2025-05-02       Makanan         50000
3  2025-05-02       Hiburan         30000

In [219]:
df_csv = pd.read_csv(filepath+filecsv,sep=',',skiprows=6)
df_csv

,id_pelanggan,nama,email,telepon,umur,bulan_lahir,tanggal_registrasi,konfirmasi_telepon,penipu,pengguna_aktif
0,1,Fakhrul Fandy Widyaningtias,fakhrulfandywidyaningtias@outlook.com,6285244454,27,Juni,2012-02-18,1,0,1
1,2,Ferdiansyah Amalina,ferdiansyahamalina@yahoo.com,6285244688,31,Agustus,2012-06-29,1,0,1
2,3,Ficky Rizkyananta,fickyrizkyananta@hotmail.com,6285244922,15,Februari,2013-06-04,1,0,1
3,4,Singgih Kharisma,singgihkharisma@hotmail.com,6285245156,49,Januari,2013-01-13,1,0,1
4,5,Jeremiah Dinanti,jeremiahdinanti@roketmail.com,6285245390,25,Januari,2012-02-15,1,0,1
...,...,...,...,...,...,...,...,...,...,...
80,81,Desi Fauziyah,desifauziyah@outlook.com,6285229563,34,Maret,2013-01-29,1,0,1
81,82,Tresna Rianita Prasojo,tresnarianitaprasojo@yahoo.com,6285222998,44,Maret,2012-05-25,0,0,1
82,83,Rarahayu Verev,rarahayuverev@outlook.com,6285216433,15,April,2013-02-22,1,0,1
83,84,Janiar Satria,janiarsatria@outlook.com,6285209868,17,Mei,2012-03-20,1,0,1
84,85,Retno Maulinda,retnomaulinda@roketmail.com,6285203303,28,November,2012-07-30,1,0,1

In [220]:
with open(filepath+filetxt, 'r') as file:
  df = pd.read_csv(file,delimiter=';')
  print(df.info())
  # print(df.head(5))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   registration_id  169 non-null    object
 1   name             169 non-null    object
 2   email            162 non-null    object
 3   phone            169 non-null    int64
 4   age              169 non-null    int64
 5   city             157 non-null    object
 6   province         169 non-null    object
 7   active           169 non-null    int64
 8   class            169 non-null    int64
 9   score            165 non-null    float64
dtypes: float64(1), int64(4), object(5)
memory usage: 13.3+ KB
None

In [221]:
df = pd.read_json(filepath+filejson)
features = df['features'].values.tolist()
df_features = pd.DataFrame(features)
properties = df_features['properties'].values.tolist()
df_properties = pd.DataFrame(properties,index=range(1,len(properties)+1))
df_properties

              name population                country coastal
1           Berlin      3.375                Germany   false
2            Tokyo      13.35                  Japan    true
3        New Delhi       9.88                  India   false
4      Los Angeles       3.92          United States    true
5           Boston       4.18          United States    true
6       Copenhagen       1.26                Denmark    true
7      Mexico City       8.85                 Mexico   false
8        Amsterdam       1.32            Netherlands   false
9          Bangkok       8.28               Thailand    true
10          Sydney       4.84              Australia    true
11          Prague       1.26         Czech Republic   false
12       Cape Town       0.43           South Africa    true
13          Taipei       2.70                 Taiwan    true
14       Hong Kong       7.23                  China    true
15        Shanghai      24.26                  China    true
16        San Juan       0.39            Puerto Rico    true
17         Nairobi       3.14                  Kenya   false
18          Bergen       0.27                 Norway    true
19        Santiago       5.15                  Chile   false
20           Busan       3.53            South Korea    true
21       Singapore       5.47  Republic of Singapore    true
22           Paris       2.24                 France   false
23  Rio de Janeiro       6.45                 Brazil    true
24      Montevideo       1.31                Uruguay    true
25         Caracas       3.27              Venezuela    true
26          Madrid       3.17                  Spain   false
27            Rome       2.87                  Italy   false
28          Athens       3.09                 Greece    true
29        Istanbul      14.10                 Turkey    true
30       Bucharest       1.88                Romania   false
31           Perth       2.02              Australia    true
32          Mumbai      12.48                  India    true
33        Helsinki       1.11                Finland    true
34       Stockholm       1.37                 Sweden    true
35       Reykjavik       0.12                Iceland    true
36       San Diego       1.38          United States    true
37         Toronto       2.62                 Canada   false
38          Moscow      12.20                 Russia   false
39          Tehran       8.15                   Iran   false
40           Cairo      10.23                  Egypt   false

Memilih baris berdasarkan index

In [236]:
a = df_properties['coastal'] == 'false'
b = df_properties['country'] == 'Germany'
df_is_coastal = df_properties[(a) & (b)]
df_is_coastal

     name population  country coastal
1  Berlin      3.375  Germany   false

In [224]:
df_csv[(df_csv['penipu'] == 1)]

,id_pelanggan,nama,email,telepon,umur,bulan_lahir,tanggal_registrasi,konfirmasi_telepon,penipu,pengguna_aktif
16,17,Rifqy Butar-butar,rifqybutar-butar@yahoo.com,6289625971,30,September,2012-01-14,1,1,1
17,18,Wahyu Hayati,wahyuhayati@gmail.com,6289627184,23,Desember,2012-09-15,1,1,1
57,58,Nadia Persadani,nadiapersadani@roketmail.com,6287833759,25,Juli,2012-10-26,1,1,1
72,73,Natasha Fadholi,natashafadholi@gmail.com,6285282083,49,April,2013-02-08,1,1,1

In [237]:
df_csv[(df_csv['umur'] > 30) & (df_csv['pengguna_aktif'] == 1)]

,id_pelanggan,nama,email,telepon,umur,bulan_lahir,tanggal_registrasi,konfirmasi_telepon,penipu,pengguna_aktif
1,2,Ferdiansyah Amalina,ferdiansyahamalina@yahoo.com,6285244688,31,Agustus,2012-06-29,1,0,1
3,4,Singgih Kharisma,singgihkharisma@hotmail.com,6285245156,49,Januari,2013-01-13,1,0,1
5,6,Ridhwan Noerani,ridhwannoerani@hotmail.com,6285245624,43,Januari,2013-05-02,1,0,1
6,7,Okky Oktaviaman,okkyoktaviaman@roketmail.com,6281906358,35,Maret,2012-04-29,1,0,1
9,10,Bob Arisa,bobarisa@yahoo.com,6281909025,40,Desember,2012-11-11,1,0,1
10,11,Omar Afini,omarafini@gmail.com,6281909914,48,November,2013-01-10,1,0,1
11,12,Sutrisno Rizal,sutrisnorizal@outlook.com,6281910803,36,Januari,2012-09-20,1,0,1
13,14,Lintang Bertauli,lintangbertauli@gmail.com,6281912581,33,April,2013-05-14,1,0,1
14,15,Reynard Ramadhansyah,reynardramadhansyah@gmail.com,6289623545,34,Mei,2012-04-24,1,0,1
15,16,Kevin Ningsih,kevinningsih@roketmail.com,6289624758,49,Oktober,2013-10-23,1,0,1
18,19,Andi Mayasopha,andimayasopha@yahoo.com,6289628397,36,Juni,2012-10-16,1,0,1
19,20,Yutama Riahdita,yutamariahdita@gmail.com,6289629610,48,Agustus,2012-03-08,1,0,1
20,21,Haikal Nurahmadhita,haikalnurahmadhita@roketmail.com,6289630823,37,Februari,2013-11-05,1,0,1
21,22,Thomas Geryance,thomasgeryance@roketmail.com,6289632036,40,Januari,2012-09-23,1,0,1
23,24,Ramanta Pasha,ramantapasha@gmail.com,6287832435,49,Januari,2013-03-29,0,0,1
24,25,Sakti Hasaniy,saktihasaniy@outlook.com,6287832669,31,Maret,2013-08-28,1,0,1
29,30,Herdaru Junaidi,herdarujunaidi@outlook.com,6287833839,50,Januari,2013-07-29,1,0,1
30,31,Eka Tiodimar,ekatiodimar@roketmail.com,6287834073,40,Maret,2012-07-08,1,0,1
31,32,Sebastian Mitsuko,sebastianmitsuko@roketmail.com,6287834307,44,April,2012-11-09,0,0,1
32,33,Rinaldy Octaza,rinaldyoctaza@outlook.com,6287834541,35,Mei,2013-06-03,0,0,1
38,39,Izhar Halim,izharhalim@gmail.com,6287881031,32,September,2013-01-23,1,0,1
39,40,Garin Sugiyanto,garinsugiyanto@yahoo.com,6287881265,33,Desember,2012-09-27,1,0,1
41,42,Geraldi Lalo,geraldilalo@hotmail.com,6287885801,50,Mei,2012-09-05,1,0,1
42,43,Yusuf Tilasnuari,yusuftilasnuari@hotmail.com,6287888069,31,Juli,2013-02-01,1,0,1
44,45,Maruto Asih,marutoasih@yahoo.com,6287892605,47,Juni,2012-01-16,1,0,1
46,47,Anton Fikri,antonfikri@hotmail.com,6287897141,38,Desember,2013-02-17,1,0,1
47,48,Anugrah Sastra,anugrahsastra@outlook.com,6287899409,35,November,2013-12-10,1,0,1
48,49,Sigit Amalia,sigitamalia@roketmail.com,6287892844,48,Maret,2013-02-23,1,0,1
49,50,Rizki Faishal Apriyani,rizkifaishalapriyani@roketmail.com,6287886279,42,Maret,2013-03-20,0,0,1
50,51,Athirah Atsila,athirahatsila@yahoo.com,6287879714,47,April,2012-11-23,1,0,1
51,52,Indah Khairunisa,indahkhairunisa@roketmail.com,6287873149,40,Mei,2012-04-01,1,0,1
54,55,Anastasia Primanelza,anastasiaprimanelza@roketmail.com,6287853454,40,Desember,2013-08-18,0,0,1
55,56,Anna Usra,annausra@roketmail.com,6287846889,42,Mei,2012-09-10,1,0,1
59,60,Hanifa Ivangkia,hanifaivangkia@gmail.com,6287820629,47,Agustus,2012-08-22,1,0,1
61,62,Auzy Narendra,auzynarendra@outlook.com,6287807499,35,November,2012-07-20,1,0,1
62,63,Rocitha Mufti,rocithamufti@roketmail.com,6285347733,33,Maret,2012-12-26,1,0,1
64,65,Puspa Fariza,puspafariza@yahoo.com,6285334603,34,April,2012-08-14,1,0,1
68,69,Salsabila Resa,salsabilaresa@hotmail.com,6285308343,32,Desember,2013-11-15,1,0,1
71,72,Bella Listyani,bellalistyani@hotmail.com,6285288648,45,Maret,2013-10-01,1,0,1
72,73,Natasha Fadholi,natashafadholi@gmail.com,6285282083,49,April,2013-02-08,1,1,1
74,75,June Andjani,juneandjani@gmail.com,6285268953,45,Desember,2013-09-01,1,0,1
78,79,Saliha Husein,salihahusein@outlook.com,6285242693,49,April,2012-01-22,1,0,1
80,81,Desi Fauziyah,desifauziyah@outlook.com,6285229563,34,Maret,2013-01-29,1,0,1
81,82,Tresna Rianita Prasojo,tresnarianitaprasojo@yahoo.com,6285222998,44,Maret,2012-05-25,0,0,1

In [244]:
bln_tertentu = df_csv['bulan_lahir'].isin(['Januari','Maret'])
df_csv[df_csv['bulan_lahir'].isin(['Januari'])]
df_csv.query('bulan_lahir in ("Januari","Maret")')

,id_pelanggan,nama,email,telepon,umur,bulan_lahir,tanggal_registrasi,konfirmasi_telepon,penipu,pengguna_aktif
3,4,Singgih Kharisma,singgihkharisma@hotmail.com,6285245156,49,Januari,2013-01-13,1,0,1
4,5,Jeremiah Dinanti,jeremiahdinanti@roketmail.com,6285245390,25,Januari,2012-02-15,1,0,1
5,6,Ridhwan Noerani,ridhwannoerani@hotmail.com,6285245624,43,Januari,2013-05-02,1,0,1
6,7,Okky Oktaviaman,okkyoktaviaman@roketmail.com,6281906358,35,Maret,2012-04-29,1,0,1
11,12,Sutrisno Rizal,sutrisnorizal@outlook.com,6281910803,36,Januari,2012-09-20,1,0,1
12,13,Hilman Azalia,hilmanazalia@hotmail.com,6281911692,17,Maret,2013-11-15,1,0,1
21,22,Thomas Geryance,thomasgeryance@roketmail.com,6289632036,40,Januari,2012-09-23,1,0,1
22,23,Muhamad Pramanda,muhamadpramanda@outlook.com,6289633249,16,Januari,2012-05-16,1,0,1
23,24,Ramanta Pasha,ramantapasha@gmail.com,6287832435,49,Januari,2013-03-29,0,0,1
24,25,Sakti Hasaniy,saktihasaniy@outlook.com,6287832669,31,Maret,2013-08-28,1,0,1
29,30,Herdaru Junaidi,herdarujunaidi@outlook.com,6287833839,50,Januari,2013-07-29,1,0,1
30,31,Eka Tiodimar,ekatiodimar@roketmail.com,6287834073,40,Maret,2012-07-08,1,0,1
48,49,Sigit Amalia,sigitamalia@roketmail.com,6287892844,48,Maret,2013-02-23,1,0,1
49,50,Rizki Faishal Apriyani,rizkifaishalapriyani@roketmail.com,6287886279,42,Maret,2013-03-20,0,0,1
62,63,Rocitha Mufti,rocithamufti@roketmail.com,6285347733,33,Maret,2012-12-26,1,0,1
63,64,Amalia Widi Abelardo,amaliawidiabelardo@outlook.com,6285341168,17,Maret,2013-01-24,1,0,1
70,71,Moerdiati Ramsihs,moerdiatiramsihs@roketmail.com,6285295213,16,Maret,2013-08-25,0,0,0
71,72,Bella Listyani,bellalistyani@hotmail.com,6285288648,45,Maret,2013-10-01,1,0,1
76,77,Amanda Idayu,amandaidayu@yahoo.com,6285255823,17,Maret,2012-01-10,0,0,1
77,78,Ovienov Asti Idrus,ovienovastiidrus@outlook.com,6285249258,15,Maret,2012-04-08,1,0,1
80,81,Desi Fauziyah,desifauziyah@outlook.com,6285229563,34,Maret,2013-01-29,1,0,1
81,82,Tresna Rianita Prasojo,tresnarianitaprasojo@yahoo.com,6285222998,44,Maret,2012-05-25,0,0,1

In [278]:
df_pelanggan = pd.read_csv(filepath+filecsv,skiprows=6)
a = (df_pelanggan['umur'] >= 25) & (df_pelanggan['umur'] <= 40)
b = df_pelanggan['penipu'] == 0
c = df_pelanggan['pengguna_aktif'] == 1
d = df_pelanggan['konfirmasi_telepon'] == 1
e = df_pelanggan['bulan_lahir'].isin(['Maret','Juni', 'September'])
pelanggan = df_pelanggan[(a) & (b) & (c) & (d) & (e)].filter(items=['nama','email','umur','bulan_lahir','telepon'])
print(f'Jumlah WP Potensial Baru : {pelanggan["nama"].count()} dari {df_pelanggan["nama"].count()}')
print(pelanggan['umur'].describe())
pelanggan

Jumlah WP Potensial Baru : 9 dari 85
count     9.000000
mean     32.555556
std       4.558265
min      25.000000
25%      31.000000
50%      33.000000
75%      35.000000
max      40.000000
Name: umur, dtype: float64

,nama,email,umur,bulan_lahir,telepon
0,Fakhrul Fandy Widyaningtias,fakhrulfandywidyaningtias@outlook.com,27,Juni,6285244454
6,Okky Oktaviaman,okkyoktaviaman@roketmail.com,35,Maret,6281906358
18,Andi Mayasopha,andimayasopha@yahoo.com,36,Juni,6289628397
24,Sakti Hasaniy,saktihasaniy@outlook.com,31,Maret,6287832669
30,Eka Tiodimar,ekatiodimar@roketmail.com,40,Maret,6287834073
38,Izhar Halim,izharhalim@gmail.com,32,September,6287881031
58,Rayhana Hidayatul,rayhanahidayatul@hotmail.com,25,Juni,6287827194
62,Rocitha Mufti,rocithamufti@roketmail.com,33,Maret,6285347733
80,Desi Fauziyah,desifauziyah@outlook.com,34,Maret,6285229563

array([27, 35, 36, 31, 40, 32, 25, 33, 34])